res <- XML::readHTMLTable(paste0('http://cran.r-project.org/web/packages/available_packages_by_name.html'), which = 1)
library(tm)
getReaders()
getSources()
v<-Corpus(VectorSource(res$V2))
v
inspect(head(v,5))
getTransformations()
View(res)
removeWords('to be or not to be',stopwords("english"))
v<-tm_map(v,removeWords,stopwords("english"))
inspect(head(v,5))
removeWords('To be or not to be.',stopwords("english"))
v<-tm_map(v,content_transformer(tolower))
v<-tm_map(v,removePunctuation)
v<-tm_map(v,stripWhitespace)
inspect(head(v,5))
wordcloud::wordcloud(v)
save.image("C:/Users/kevser/Desktop/Uygulamalar/AraSonuc10.RData")
v<-tm_map(v,removeNumbers)
tdm<-TermDocumentMatrix(v)
inspect(tdm[1:10,1:15])
findFreqTerms(tdm,lowfreq=100)
myStopwords<-c('the','via','package','based','using')
v<-tm_map(v,removeWords,myStopwords)
tdm<-TermDocumentMatrix(v)
findFreqTerms(tdm,lowfreq=100)
install.packages("SnowballC")
library(SnowballC)
wordStem(c('dogs','walk','print','printed','printer','printing'))
d<-v
save.image("C:/Users/kevser/Desktop/Uygulamalar/AraSonuc3.RData")
v<-tm_map(v,stemDocument,language="english")
save.image("C:/Users/kevser/Desktop/Uygulamalar/AraSonuc.RData")
stemCompletion2 <- function(x, dictionary) {
  x <- unlist(strsplit(as.character(x), " "))
  x <- x[x != ""]
  x <- stemCompletion(x, dictionary=dictionary)
  x <- paste(x, sep="", collapse=" ")
  PlainTextDocument(stripWhitespace(x))
}
v<-lapply(v,stemCompletion2, dictionary=d)
save.image("C:/Users/kevser/Desktop/Uygulamalar/AraSonuc2.RData")
v<-Corpus(VectorSource(v))
tdm<-TermDocumentMatrix(v)
findFreqTerms(tdm,lowfreq = 100)
tdm
dtm<-TermDocumentMatrix(v)
m<-as.matrix(dtm)
v<-sort(rowSums(m),decreasing = TRUE)
d<-data.frame(word=names(v),freq=v)
head(d,10)
save.image("C:/Users/kevser/Desktop/Uygulamalar/AraSonuc4.RData")
if(!require("RColorBrewer")){
  install.packages("RColorBrewer")
  library(RColorBrewer)
}
set.seed(1234)
wordcloud::wordcloud(words=d$word,freq=d$freq, min.freq = 1, max.words = 200,random.order=FALSE,rot.per=0.35,colors=brewer.pal(8,"Dark2"))
save.image("C:/Users/kevser/Desktop/Uygulamalar/AraSonuc5.RData")
barplot(d[1:10,]$freq,las=2,names.arg = d[1:10,]$word, col="lightblue", main="Most frequent words",ylab="Word frequencies")
save.image("C:/Users/kevser/Desktop/Uygulamalar/AraSonuc6.RData")