hepsi: derle calistir

derle:
	g++ -I ./include/ -o ./lib/Dugum.o -c ./src/Dugum.cpp
	g++ -I ./include/ -o ./lib/HuffmanTree.o -c ./src/HuffmanTree.cpp
	g++ -I ./include/ -o ./bin/Test ./lib/HuffmanTree.o ./lib/Dugum.o ./src/Test.cpp

calistir:
	./bin/Test